
stages:
    - pull
    - build stage 1
    - build stage 2
    - build stage 3
    - build stage 4
    - build stage 5
    - build stage 6
    - build stage 7
    - build stage 8
    - build stage 9
    - build stage 10
    - build stage 11
    - push
    - cleanup

before_script:
    - docker info


pull:
    stage: pull
    script:
        - 'docker pull csanchez/jenkins-swarm-slave || :'
        - 'docker pull debian:8.1 || :'
        - 'docker pull dock0/arch || :'
        - 'docker pull evarga/jenkins-slave || :'
        - 'docker pull java:8-jdk || :'
        - 'docker pull jenkins:2.32.3 || :'
        - 'docker pull phusion/baseimage:0.9.17 || :'
        - 'docker pull pitkley/jenkins-slave-texlive || :'
        - 'docker pull pitkley/jenkins-slave-texlive:swarm || :'
        - 'docker pull pitkley/jenkins-swarm-slave || :'
        - 'docker pull python:2.7 || :'

arch-makepkg:latest:build:
    stage: build stage 1
    only:
        - master
        - /ci-/
        - /-ci/
        - /arch-makepkg/
    script:
        - cd arch-makepkg
        - docker build -t pitkley/arch-makepkg:latest .

arch-makepkg:latest:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/arch-makepkg:latest

jenkins-dood:2:build:
    stage: build stage 1
    only:
        - master
        - /ci-/
        - /-ci/
        - /jenkins-dood/
    script:
        - cd jenkins-dood/2
        - docker build -t pitkley/jenkins-dood:2 .

jenkins-dood:2:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/jenkins-dood:2

jenkins-slave-texlive:latest:build:
    stage: build stage 1
    only:
        - master
        - /ci-/
        - /-ci/
        - /jenkins-slave-texlive/
    script:
        - cd jenkins-slave-texlive
        - docker build -t pitkley/jenkins-slave-texlive:latest .

jenkins-slave-texlive:latest:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/jenkins-slave-texlive:latest

jenkins-swarm-slave:latest:build:
    stage: build stage 1
    only:
        - master
        - /ci-/
        - /-ci/
        - /jenkins-swarm-slave/
    script:
        - cd jenkins-swarm-slave
        - docker build -t pitkley/jenkins-swarm-slave:latest .

jenkins-swarm-slave:latest:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/jenkins-swarm-slave:latest

libpst:latest:build:
    stage: build stage 1
    only:
        - master
        - /ci-/
        - /-ci/
        - /libpst/
    script:
        - cd libpst
        - docker build -t pitkley/libpst:latest .

libpst:latest:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/libpst:latest

platformio:2:build:
    stage: build stage 1
    only:
        - master
        - /ci-/
        - /-ci/
        - /platformio/
    script:
        - cd platformio/2
        - docker build -t pitkley/platformio:2 .

platformio:2:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/platformio:2

samba-ad-dc:latest:build:
    stage: build stage 1
    only:
        - master
        - /ci-/
        - /-ci/
        - /samba-ad-dc/
    script:
        - cd samba-ad-dc
        - docker build -t pitkley/samba-ad-dc:latest .

samba-ad-dc:latest:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/samba-ad-dc:latest

jenkins-dood:2.32:build:
    stage: build stage 2
    only:
        - master
        - /ci-/
        - /-ci/
        - /jenkins-dood/
    script:
        - cd jenkins-dood/2.32
        - docker build -t pitkley/jenkins-dood:2.32 .

jenkins-dood:2.32:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/jenkins-dood:2.32

jenkins-slave-texlive-personal:latest:build:
    stage: build stage 2
    only:
        - master
        - /ci-/
        - /-ci/
        - /jenkins-slave-texlive-personal/
    script:
        - cd jenkins-slave-texlive-personal
        - docker build -t pitkley/jenkins-slave-texlive-personal:latest .

jenkins-slave-texlive-personal:latest:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/jenkins-slave-texlive-personal:latest

jenkins-slave-texlive:swarm:build:
    stage: build stage 2
    only:
        - master
        - /ci-/
        - /-ci/
        - /jenkins-slave-texlive/
    script:
        - cd jenkins-slave-texlive/swarm
        - docker build -t pitkley/jenkins-slave-texlive:swarm .

jenkins-slave-texlive:swarm:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/jenkins-slave-texlive:swarm

maven-swarm:3.3:build:
    stage: build stage 2
    only:
        - master
        - /ci-/
        - /-ci/
        - /maven-swarm/
    script:
        - cd maven-swarm/3.3
        - docker build -t pitkley/maven-swarm:3.3 .

maven-swarm:3.3:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/maven-swarm:3.3

maven-swarm:3:build:
    stage: build stage 2
    only:
        - master
        - /ci-/
        - /-ci/
        - /maven-swarm/
    script:
        - cd maven-swarm/3
        - docker build -t pitkley/maven-swarm:3 .

maven-swarm:3:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/maven-swarm:3

platformio:2.11.2:build:
    stage: build stage 2
    only:
        - master
        - /ci-/
        - /-ci/
        - /platformio/
    script:
        - cd platformio/2.11.2
        - docker build -t pitkley/platformio:2.11.2 .

platformio:2.11.2:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/platformio:2.11.2

python-swarm:2.6:build:
    stage: build stage 2
    only:
        - master
        - /ci-/
        - /-ci/
        - /python-swarm/
    script:
        - cd python-swarm/2.6
        - docker build -t pitkley/python-swarm:2.6 .

python-swarm:2.6:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/python-swarm:2.6

python-swarm:2:build:
    stage: build stage 2
    only:
        - master
        - /ci-/
        - /-ci/
        - /python-swarm/
    script:
        - cd python-swarm/2
        - docker build -t pitkley/python-swarm:2 .

python-swarm:2:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/python-swarm:2

jenkins-dood:2.32.3:build:
    stage: build stage 3
    only:
        - master
        - /ci-/
        - /-ci/
        - /jenkins-dood/
    script:
        - cd jenkins-dood/2.32.3
        - docker build -t pitkley/jenkins-dood:2.32.3 .

jenkins-dood:2.32.3:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/jenkins-dood:2.32.3

jenkins-slave-texlive-personal:swarm:build:
    stage: build stage 3
    only:
        - master
        - /ci-/
        - /-ci/
        - /jenkins-slave-texlive-personal/
    script:
        - cd jenkins-slave-texlive-personal/swarm
        - docker build -t pitkley/jenkins-slave-texlive-personal:swarm .

jenkins-slave-texlive-personal:swarm:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/jenkins-slave-texlive-personal:swarm

maven-swarm:3.3.9:build:
    stage: build stage 3
    only:
        - master
        - /ci-/
        - /-ci/
        - /maven-swarm/
    script:
        - cd maven-swarm/3.3.9
        - docker build -t pitkley/maven-swarm:3.3.9 .

maven-swarm:3.3.9:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/maven-swarm:3.3.9

platformio:3:build:
    stage: build stage 3
    only:
        - master
        - /ci-/
        - /-ci/
        - /platformio/
    script:
        - cd platformio/3
        - docker build -t pitkley/platformio:3 .

platformio:3:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/platformio:3

python-swarm:2.6.9:build:
    stage: build stage 3
    only:
        - master
        - /ci-/
        - /-ci/
        - /python-swarm/
    script:
        - cd python-swarm/2.6.9
        - docker build -t pitkley/python-swarm:2.6.9 .

python-swarm:2.6.9:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/python-swarm:2.6.9

jenkins-dood:latest:build:
    stage: build stage 4
    only:
        - master
        - /ci-/
        - /-ci/
        - /jenkins-dood/
    script:
        - cd jenkins-dood/latest
        - docker build -t pitkley/jenkins-dood:latest .

jenkins-dood:latest:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/jenkins-dood:latest

maven-swarm:latest:build:
    stage: build stage 4
    only:
        - master
        - /ci-/
        - /-ci/
        - /maven-swarm/
    script:
        - cd maven-swarm/latest
        - docker build -t pitkley/maven-swarm:latest .

maven-swarm:latest:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/maven-swarm:latest

platformio:3.0.1:build:
    stage: build stage 4
    only:
        - master
        - /ci-/
        - /-ci/
        - /platformio/
    script:
        - cd platformio/3.0.1
        - docker build -t pitkley/platformio:3.0.1 .

platformio:3.0.1:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/platformio:3.0.1

python-swarm:2.7:build:
    stage: build stage 4
    only:
        - master
        - /ci-/
        - /-ci/
        - /python-swarm/
    script:
        - cd python-swarm/2.7
        - docker build -t pitkley/python-swarm:2.7 .

python-swarm:2.7:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/python-swarm:2.7

platformio:latest:build:
    stage: build stage 5
    only:
        - master
        - /ci-/
        - /-ci/
        - /platformio/
    script:
        - cd platformio/latest
        - docker build -t pitkley/platformio:latest .

platformio:latest:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/platformio:latest

python-swarm:2.7.12:build:
    stage: build stage 5
    only:
        - master
        - /ci-/
        - /-ci/
        - /python-swarm/
    script:
        - cd python-swarm/2.7.12
        - docker build -t pitkley/python-swarm:2.7.12 .

python-swarm:2.7.12:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/python-swarm:2.7.12

python-swarm:3:build:
    stage: build stage 6
    only:
        - master
        - /ci-/
        - /-ci/
        - /python-swarm/
    script:
        - cd python-swarm/3
        - docker build -t pitkley/python-swarm:3 .

python-swarm:3:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/python-swarm:3

python-swarm:3.4:build:
    stage: build stage 7
    only:
        - master
        - /ci-/
        - /-ci/
        - /python-swarm/
    script:
        - cd python-swarm/3.4
        - docker build -t pitkley/python-swarm:3.4 .

python-swarm:3.4:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/python-swarm:3.4

python-swarm:3.4.5:build:
    stage: build stage 8
    only:
        - master
        - /ci-/
        - /-ci/
        - /python-swarm/
    script:
        - cd python-swarm/3.4.5
        - docker build -t pitkley/python-swarm:3.4.5 .

python-swarm:3.4.5:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/python-swarm:3.4.5

python-swarm:3.5:build:
    stage: build stage 9
    only:
        - master
        - /ci-/
        - /-ci/
        - /python-swarm/
    script:
        - cd python-swarm/3.5
        - docker build -t pitkley/python-swarm:3.5 .

python-swarm:3.5:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/python-swarm:3.5

python-swarm:3.5.2:build:
    stage: build stage 10
    only:
        - master
        - /ci-/
        - /-ci/
        - /python-swarm/
    script:
        - cd python-swarm/3.5.2
        - docker build -t pitkley/python-swarm:3.5.2 .

python-swarm:3.5.2:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/python-swarm:3.5.2

python-swarm:latest:build:
    stage: build stage 11
    only:
        - master
        - /ci-/
        - /-ci/
        - /python-swarm/
    script:
        - cd python-swarm/latest
        - docker build -t pitkley/python-swarm:latest .

python-swarm:latest:push:
    stage: push
    only:
        - master
    script:
        - docker push pitkley/python-swarm:latest


cleanup unused docker images:
    stage: cleanup
    allow_failure: true
    script: >
        docker images --format '{{.ID}} {{.Tag}}' |
        awk '$2 ~ /<none>/ {print $1}' |
        xargs docker rmi

